name: 'chart-releaser'
author: vapor-ware
description: 'Automated version manager for Helm charts'
inputs:
  path:
    description: 'Arguments passed to chart-releaser'
    required: false
outputs:
  chart-releaser-output:
    description: 'The output if chart-releaser fails'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'check-circle'
  color: 'green'
